/**
 * Bundled scenarios: the mocked shell contexts the preview renders against.
 *
 * These double as the parity harness's fixtures — each one is materialised as
 * a real directory (git repo, files, env) so real starship can be run against
 * it and compared with the engine's output. Keep them in sync with
 * `tests/parity/fixtures.ts`.
 */

import type { Scenario } from "./types";

const BASE: Omit<Scenario, "id" | "label" | "description"> = {
  path: "/Users/you",
  home: "/Users/you",
  readOnly: false,
  files: [],
  status: 0,
  cmdDurationMs: 0,
  jobs: 0,
  username: "you",
  hostname: "laptop",
  ssh: false,
  isRoot: false,
  shell: "zsh",
  keymap: "insert",
  time: "2026-08-18T09:41:00",
  terminalWidth: 80,
  toolVersions: {},
  env: {},
  os: { name: "Macos", type: "Macos" },
};

const SCENARIOS: Scenario[] = [
  {
    ...BASE,
    id: "simple",
    label: "Home directory",
    description: "A clean prompt in the home directory, previous command succeeded.",
  },
  {
    ...BASE,
    id: "dirty-repo",
    label: "Dirty git repo",
    description:
      "A feature branch with staged, modified and untracked files, two commits ahead.",
    path: "/Users/you/code/app/src",
    files: ["engine", "scenarios", "fonts.ts"],
    git: {
      branch: "feat/live-preview",
      commit: "a1b2c3d",
      detached: false,
      ahead: 2,
      behind: 0,
      staged: 1,
      modified: 3,
      deleted: 0,
      renamed: 0,
      untracked: 2,
      conflicted: 0,
      stashed: 1,
      root: "/Users/you/code/app",
      hasRemote: true,
      remoteBranch: "feat/live-preview",
      remoteName: "origin",
    },
    toolVersions: { nodejs: "22.19.0" },
  },
  {
    ...BASE,
    id: "failed-command",
    label: "Failed command",
    description: "Previous command exited 127 after 3.2 seconds, with a background job.",
    path: "/Users/you/code/scratch",
    files: ["notes.txt"],
    status: 127,
    cmdDurationMs: 3210,
    jobs: 1,
  },
  {
    ...BASE,
    id: "polyglot",
    label: "Polyglot project",
    description: "A repo carrying Node, Python, Rust and Docker markers at once.",
    path: "/Users/you/code/polyglot",
    files: [
      "package.json",
      "pyproject.toml",
      "Cargo.toml",
      "Dockerfile",
      "go.mod",
      "src",
      "main.py",
      "lib.rs",
    ],
    git: {
      branch: "main",
      commit: "9f8e7d6",
      detached: false,
      ahead: 0,
      behind: 0,
      staged: 0,
      modified: 0,
      deleted: 0,
      renamed: 0,
      untracked: 0,
      conflicted: 0,
      stashed: 0,
      root: "/Users/you/code/polyglot",
      hasRemote: true,
      remoteBranch: "main",
      remoteName: "origin",
    },
    toolVersions: {
      nodejs: "22.19.0",
      python: "3.13.1",
      rust: "1.84.0",
      golang: "1.24.0",
    },
    python: { virtualenv: "polyglot" },
  },
  {
    ...BASE,
    id: "ssh-root",
    label: "SSH as root",
    description: "A remote session as root, so username and hostname both show.",
    path: "/etc/nginx",
    files: ["nginx.conf", "sites-enabled"],
    username: "root",
    hostname: "web-01",
    ssh: true,
    isRoot: true,
    readOnly: false,
    shell: "bash",
    os: { name: "Ubuntu", type: "Ubuntu" },
    env: { SSH_CONNECTION: "10.0.0.4 52244 10.0.0.9 22" },
  },
  {
    ...BASE,
    id: "cloud",
    label: "Cloud & Kubernetes",
    description: "AWS profile, GCP project, a Kubernetes context and a Terraform workspace.",
    path: "/Users/you/code/infra",
    files: ["main.tf", "variables.tf", ".terraform"],
    git: {
      branch: "main",
      commit: "1122334",
      detached: false,
      ahead: 0,
      behind: 1,
      staged: 0,
      modified: 1,
      deleted: 0,
      renamed: 0,
      untracked: 0,
      conflicted: 0,
      stashed: 0,
      root: "/Users/you/code/infra",
      hasRemote: true,
      remoteBranch: "main",
      remoteName: "origin",
    },
    aws: { profile: "production", region: "ap-southeast-2" },
    gcloud: { account: "you@example.com", project: "example-prod", region: "australia-southeast1" },
    kubernetes: { context: "prod-cluster", namespace: "web", cluster: "prod-cluster" },
    terraform: { workspace: "production" },
    toolVersions: { terraform: "1.10.3" },
  },
  {
    ...BASE,
    id: "rebase",
    label: "Rebase in progress",
    description: "An interactive rebase paused on a conflict.",
    path: "/Users/you/code/starship",
    files: ["package.json", "src", "README.md"],
    status: 1,
    git: {
      branch: "feat/engine",
      commit: "deadbee",
      detached: false,
      state: "REBASING",
      stateProgress: { current: 2, total: 5 },
      ahead: 0,
      behind: 0,
      staged: 0,
      modified: 1,
      deleted: 0,
      renamed: 0,
      untracked: 0,
      conflicted: 2,
      stashed: 0,
      root: "/Users/you/code/starship",
      hasRemote: true,
      remoteBranch: "feat/engine",
      remoteName: "origin",
    },
    toolVersions: { nodejs: "22.19.0" },
  },
];

export const DEFAULT_SCENARIO_ID = "dirty-repo";

export function getScenario(id: string): Scenario {
  return SCENARIOS.find((s) => s.id === id) ?? SCENARIOS[0];
}
