/**
 * One-line explanations of what each module puts in your prompt.
 *
 * Extracted from starship's own documentation (docs/config/README.md) rather
 * than written from scratch, so the wording stays true to upstream; a handful
 * are shortened or supplied by hand where the docs open with a paragraph too
 * long to read inside a row. Regenerate alongside a schema sync.
 */

export const MODULE_DESCRIPTIONS: Record<string, string> = {
  username: "Shows active user's username",
  hostname: "Shows the system hostname",
  localip: "Shows the IPv4 address of the primary network interface",
  shlvl: "Shows how many shells deep you are nested",
  singularity: "Shows the current Singularity image, if inside a container and $SINGULARITY_NAME is set",
  kubernetes: "Shows the active Kubernetes context and namespace",
  nats: "Shows the selected NATS context",
  directory: "Shows the path to your current directory, truncated to three parent folders",
  vcs: "Uses the first detected version-control system and renders its configured modules",
  vcsh: "Displays the current active VCSH repository",
  fossil_branch: "Shows the name of the active branch of the check-out in your current directory",
  fossil_metrics: "Will show the number of added and deleted lines in the check-out in your current directory",
  git_branch: "Shows the active branch of the repo in your current directory",
  git_commit: "Shows the current commit hash and also the tag (if any) of the repo in your current directory",
  git_state: "Shows what operation is in progress — rebase, merge, cherry-pick, bisect or revert",
  git_metrics: "Will show the number of added and deleted lines in the current git repository",
  git_status: "Shows symbols representing the state of the repo in your current directory",
  hg_branch: "Shows the active branch and topic of the repo in your current directory",
  hg_state: "Shows the Mercurial operation in progress, such as merging or rebasing",
  pijul_channel: "Shows the active channel of the repo in your current directory",
  docker_context: "Shows the active Docker context when it is not the default",
  package: "Is shown when the current directory is the repository for a package, and shows its current version",
  bun: "Shows the currently installed version of the bun JavaScript runtime",
  c: "Shows some information about your C compiler",
  cmake: "Shows the currently installed version of CMake",
  cobol: "Shows the currently installed version of COBOL",
  cpp: "Shows some information about your C++ compiler",
  daml: "Shows the currently used Daml SDK version when you are in the root directory of your Daml project",
  dart: "Shows the currently installed version of Dart",
  deno: "Shows you your currently installed version of Deno",
  dotnet: "Shows the relevant version of the .NET Core SDK for the current directory",
  elixir: "Shows the currently installed version of Elixir and Erlang/OTP",
  elm: "Shows the currently installed version of Elm",
  erlang: "Shows the currently installed version of Erlang/OTP",
  fennel: "Shows the currently installed version of Fennel",
  fortran: "Shows the current compiler version of Fortran",
  gleam: "Shows the currently installed version of Gleam",
  golang: "Shows the currently installed version of Go",
  gradle: "Shows the version of the Gradle Wrapper currently used in the project directory",
  haskell: "Finds the current selected GHC version and/or the selected Stack snapshot",
  haxe: "Shows the currently installed version of Haxe",
  helm: "Shows the currently installed version of Helm",
  java: "Shows the currently installed version of Java",
  julia: "Shows the currently installed version of Julia",
  kotlin: "Shows the currently installed version of Kotlin",
  lua: "Shows the currently installed version of Lua",
  maven: "Indicates the presence of a Maven project in the current directory",
  mojo: "Shows the current version of Mojo programming language installed",
  nim: "Shows the currently installed version of Nim",
  nodejs: "Shows the currently installed version of Node.js",
  ocaml: "Shows the currently installed version of OCaml",
  odin: "Shows the currently installed version of Odin",
  opa: "Shows the currently installed version of the OPA tool",
  perl: "Shows the currently installed version of Perl",
  php: "Shows the currently installed version of PHP",
  pulumi: "Shows the current username, selected Pulumi Stack, and version",
  purescript: "Shows the currently installed version of PureScript version",
  python: "Shows the currently installed version of Python and the current Python virtual environment if one is activated",
  quarto: "Shows the current installed version of Quarto used in a project",
  raku: "Shows the currently installed version of Raku",
  rlang: "Shows the currently installed version of R",
  red: "By default the red module shows the currently installed version of Red",
  ruby: "By default the ruby module shows the currently installed version of Ruby",
  rust: "By default the rust module shows the currently installed version of Rust",
  scala: "Shows the currently installed version of Scala",
  solidity: "Shows the currently installed version of Solidity The module will be shown",
  swift: "By default the swift module shows the currently installed version of Swift",
  terraform: "Shows the currently selected Terraform workspace and version",
  typst: "Shows the current installed version of Typst used in a project",
  vlang: "Shows you your currently installed version of V",
  vagrant: "Shows the currently installed version of Vagrant",
  xmake: "Shows the currently installed version of XMake",
  zig: "By default the zig module shows the currently installed version of Zig",
  buf: "Shows the currently installed version of Buf",
  guix_shell: "Shows the guix-shell environment",
  nix_shell: "Shows the nix-shell environment",
  conda: "Shows the current Conda environment, if $CONDA_DEFAULT_ENV is set",
  pixi: "Shows the Pixi version and the active environment",
  meson: "Shows the current Meson developer environment status",
  spack: "Shows the current Spack environment, if $SPACK_ENV is set",
  memory_usage: "Shows current system memory and swap usage",
  aws: "Shows the current AWS region and profile and an expiration timer when using temporary credentials",
  gcloud: "Shows the current configuration for gcloud CLI",
  openstack: "Shows the current OpenStack cloud and project",
  azure: "Shows the current Azure Subscription",
  direnv: "Shows whether the current directory's .envrc is loaded and allowed",
  env_var: "Shows the value of an environment variable you choose",
  mise: "Shows the current mise health as reported by running mise doctor",
  crystal: "Shows the currently installed version of Crystal",
  custom: "Shows the output of an arbitrary command you define",
  sudo: "Shows whether cached sudo credentials are currently active",
  cmd_duration: "Shows how long the last command took to execute",
  line_break: "Separates the prompt into two lines",
  jobs: "Shows the current number of jobs running",
  battery: "Shows how charged the device's battery is and its current charging status",
  time: "Shows the current **local** time",
  status: "Shows the exit code of the previous command",
  container: "Displays a symbol and container name, if inside a container",
  netns: "Shows the active Linux network namespace",
  os: "Shows the current operating system",
  shell: "Shows an indicator for currently used shell",
  character: "Shows a character (usually an arrow) beside where the text is entered in your terminal",
};

export function describeModule(name: string): string | undefined {
  if (name === "all") return "Every module not named elsewhere in this format";
  if (name.startsWith("env_var.")) {
    return `Shows the value configured by the “${name.slice("env_var.".length)}” environment-variable instance`;
  }
  if (name.startsWith("custom.")) {
    return `Runs the “${name.slice("custom.".length)}” custom command`;
  }
  return MODULE_DESCRIPTIONS[name];
}
