import { describe, expect, it } from "vitest";
import { DEFAULT_CONFIG, resolveDefaults } from "./defaults";
import { PRESETS } from "./presets";
import { parseConfig, serialiseConfig } from "./toml";
import type { ModuleDefinition } from "@/lib/engine/modules/types";
import type { StarshipConfig } from "@/lib/engine/prompt";

function reparse(config: StarshipConfig, full = false): StarshipConfig {
  const result = parseConfig(serialiseConfig(config, { full }));
  if (!result.ok) throw new Error(`round trip failed: ${result.error}`);
  return result.config;
}

describe("parseConfig", () => {
  it("parses a config into plain data", () => {
    const result = parseConfig('add_newline = false\n\n[aws]\nsymbol = "AWS "\n');
    expect(result).toEqual({
      ok: true,
      config: { add_newline: false, aws: { symbol: "AWS " } },
    });
  });

  it("reports the line of a syntax error", () => {
    const result = parseConfig('add_newline = true\n[aws\nsymbol = "x"\n');
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.line).toBe(2);
    expect(result.error).toBeTruthy();
  });

  it("accepts an empty document", () => {
    expect(parseConfig("")).toEqual({ ok: true, config: {} });
  });

  it("keeps multi-line format strings intact", () => {
    // TOML drops the newline immediately after `"""`, and a trailing backslash
    // swallows the line break — how starship configs wrap a long `format`.
    const result = parseConfig('format = """\n$directory\\\n$character"""\n');
    expect(result.ok && result.config.format).toBe("$directory$character");
  });
});

describe("serialiseConfig", () => {
  it("emits a header and nothing else for a default config", () => {
    const toml = serialiseConfig({});
    expect(toml).toContain(
      "# starship.toml — generated by Starship Prompt Builder (https://starship.ndl.au)",
    );
    expect(toml.split("\n").filter((l) => l && !l.startsWith("#"))).toEqual([]);
  });

  it("omits the header on request", () => {
    expect(serialiseConfig({ add_newline: false }, { header: false })).toBe(
      "add_newline = false\n",
    );
  });

  it("writes only what differs from starship's defaults", () => {
    const toml = serialiseConfig({
      // Both of these are starship's own defaults and must not be written.
      add_newline: true,
      aws: { symbol: "☁️  ", style: "bold red" },
    });
    expect(toml).not.toContain("add_newline");
    expect(toml).not.toContain("symbol");
    expect(toml).toContain('style = "bold red"');
  });

  it("drops a module table that reduces to nothing", () => {
    expect(serialiseConfig({ aws: { symbol: "☁️  " } }, { header: false })).toBe("");
  });

  it("emits root scalars before module tables", () => {
    const toml = serialiseConfig(
      { git_branch: { symbol: "b " }, add_newline: false, palette: "mine" },
      { header: false },
    );
    expect(toml).toBe(
      ['add_newline = false', 'palette = "mine"', "", "[git_branch]", 'symbol = "b "', ""].join(
        "\n",
      ),
    );
  });

  it("orders keys the same way regardless of input order", () => {
    const a: StarshipConfig = { zig: { symbol: "z" }, aws: { symbol: "a" }, palette: "p" };
    const b: StarshipConfig = { palette: "p", aws: { symbol: "a" }, zig: { symbol: "z" } };
    expect(serialiseConfig(a)).toBe(serialiseConfig(b));
  });

  it("is deterministic across repeated exports", () => {
    const config = { format: "$directory$character", directory: { style: "cyan" } };
    expect(serialiseConfig(config)).toBe(serialiseConfig(config));
  });

  it("emits every resolved value when full", () => {
    const toml = serialiseConfig({ aws: { style: "bold red" } }, { full: true });
    expect(toml).toContain("add_newline = true");
    expect(toml).toContain('style = "bold red"');
    expect(toml).toContain('expiration_symbol = "X"');
    // Instance maps stay empty unless the user has instances, so no bare header.
    expect(toml).not.toContain("[env_var]");
    expect(toml).not.toContain("[custom]");
    expect(parseConfig(toml).ok).toBe(true);
  });

  it("diffs against a supplied module registry's defaults", () => {
    const modules: ModuleDefinition[] = [
      {
        name: "aws",
        defaults: { format: "$symbol", symbol: "AWS ", disabled: false },
        evaluate: () => null,
      },
    ];
    const defaults = resolveDefaults(modules);
    // Identical to the registry default, so nothing to write...
    expect(serialiseConfig({ aws: { symbol: "AWS " } }, { defaults, header: false })).toBe("");
    // ...but it differs from the schema default, so the default diff keeps it.
    expect(serialiseConfig({ aws: { symbol: "AWS " } }, { header: false })).toContain(
      'symbol = "AWS "',
    );
  });
});

describe("round trips", () => {
  it("preserves unknown root keys", () => {
    const config = { some_future_option: 42, "$schema": "https://starship.rs/config-schema.json" };
    expect(reparse(config)).toEqual(config);
  });

  it("preserves unknown module tables", () => {
    const config = { brand_new_module: { format: "$x", weird: [1, 2, 3] } };
    expect(reparse(config)).toEqual(config);
  });

  it("preserves unknown options inside a known module", () => {
    const config = { aws: { future_option: true, nested: { a: "b" } } };
    expect(reparse(config)).toEqual(config);
  });

  it("preserves unknown keys even when every known option is a default", () => {
    const config = { aws: { symbol: "☁️  ", mystery: "keep me" } };
    expect(reparse(config)).toEqual({ aws: { mystery: "keep me" } });
  });

  it("survives a second round trip unchanged", () => {
    const config = { palette: "p", brand_new_module: { a: 1 }, aws: { style: "red" } };
    const once = serialiseConfig(config);
    expect(serialiseConfig(reparse(config))).toBe(once);
  });

  it("preserves Nerd Font glyphs and trailing spaces", () => {
    // All non-default values, so a minimal export must keep every one.
    const config = {
      character: { success_symbol: "[❯](bold purple)" },
      // Nerd Font Private Use Area glyph plus the trailing space starship
      // relies on for spacing — easy to lose to an over-eager trim.
      directory: { home_symbol: "\ue5fe " },
      git_branch: { symbol: "🌱 " },
    };
    const back = reparse(config);
    expect(back).toEqual(config);
    expect((back.directory as Record<string, string>).home_symbol).toBe("\ue5fe ");
  });

  it("preserves multi-line format strings", () => {
    const config = { format: "$username\n$directory\n$character" };
    expect(reparse(config)).toEqual(config);
  });

  it("preserves nested palettes", () => {
    const config = { palette: "gruvbox", palettes: { gruvbox: { colour0: "#282828" } } };
    expect(reparse(config)).toEqual(config);
  });

  it("preserves user-named env_var and custom instances", () => {
    const config = {
      env_var: { VIMSHELL: { format: "[$env_value]($style)", variable: "SHELL" } },
      custom: { giturl: { command: "git remote get-url origin", when: "git remote" } },
    };
    expect(reparse(config)).toEqual(config);
  });

  it("preserves a newly created named instance before any option is changed", () => {
    const config = {
      format: "${env_var.SHELL}${custom.project}",
      env_var: { SHELL: {} },
      custom: { project: {} },
    };
    const toml = serialiseConfig(config, { header: false });
    expect(toml).toContain("[env_var.SHELL]");
    expect(toml).toContain("[custom.project]");
    expect(parseConfig(toml)).toEqual({ ok: true, config });
  });

  it("preserves arrays of tables", () => {
    const config = { battery: { display: [{ threshold: 20, style: "bold yellow" }] } };
    expect(reparse(config)).toEqual(config);
  });

  it.each(PRESETS.map((p) => p.id))("round-trips the %s preset losslessly", (id) => {
    const preset = PRESETS.find((p) => p.id === id);
    if (!preset) throw new Error(`missing preset ${id}`);

    const parsed = parseConfig(preset.toml);
    expect(parsed.ok).toBe(true);
    if (!parsed.ok) return;

    // A minimal export drops values a preset restates at their default, so
    // compare against the resolved config rather than the raw preset.
    const exported = reparse(parsed.config);
    for (const [key, value] of Object.entries(parsed.config)) {
      if (typeof value !== "object" || value === null || Array.isArray(value)) {
        const isDefault = value === DEFAULT_CONFIG[key];
        expect(isDefault || exported[key] === value, `${id}: ${key}`).toBe(true);
        continue;
      }
      for (const [option, optionValue] of Object.entries(value)) {
        const defaults = DEFAULT_CONFIG[key] as Record<string, unknown> | undefined;
        if (defaults && JSON.stringify(defaults[option]) === JSON.stringify(optionValue)) continue;
        const table = exported[key] as Record<string, unknown> | undefined;
        expect(JSON.stringify(table?.[option]), `${id}: ${key}.${option}`).toBe(
          JSON.stringify(optionValue),
        );
      }
    }
  });
});
